### PR TITLE
Update to ember-cli 3.5.1

### PR DESCRIPTION
**Pull request by Gaurav0**
This does a complete rebase against ember-cli/stable branch as well, as you discussed doing in this PR: https://github.com/mike-north/ember-new-output/pull/2  (That's why it won't merge automatically from github). To update, simply checkout the branch locally and push --force to the master or stable branch in your repo, as you would prefer.

### CODE REVIEW

**Comment by Gaurav0** [comment]
Note: I have a commit message and a type, but can't figure out how to satisfy commitlint.

**Comment by mike-north** [comment]
> Note: I have a commit message and a type, but can't figure out how to satisfy commitlint.

@Gaurav0 see: https://conventionalcommits.org

**Comment by Gaurav0** [comment]
@mike-north updated

**Comment by mike-north** [comment]
I'm hoping that we won't have to keep this fork updated in this way, since it's one more thing to maintain with each e-cli release.

https://github.com/ember-cli/ember-cli/issues/8172 is really what we really need to push for

**Comment by Gaurav0** [comment]
While I agree, I was hoping we could do this in the meantime.

**Comment by mike-north** [comment]
We're updated to ember 3.6.0 now. I prefer to keep rebasing the CSB changes on top of tagged commits in the official ember-new-output, so the diff between this fork and the official repo is 100% clear.

Unfortunately there's no good development workflow for this kind of thing

**Pull request closed without merging**
